

const ModulesData = [
    {   
        id:1,
        title:"Introduction to Stock Markets",
        desc:'The stock market can be crucial for achieving financial security. In this module, you will learn how to begin investing in the stock market, understand its fundamentals and operations, and become familiar with the various intermediaries involved.',
        chapters:'5 chapters',
        color:'border-t-orange-400',
        path:'/modules/md?name=intro-stock-markets'
    },
    {
        id:2,
        title:"Fundamental Analysis",
        desc:'Fundamental analysis is a method of evaluating a security in an attempt to measure its intrinsic value, by examining financial factors. In this module, you will learn how to analyze the financial statements of a company, understand the various financial ratios, and evaluate the company’s performance.',
        chapters:'5 chapters',
        color:'border-t-green-400',
        path:'/modules/md?name=fundamental-analysis'
    },
    {
        id:3,
        title:"Technical Analysis",
        desc:'Technical Analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. In this module, you will learn how to read stock charts, identify trends, and use technical indicators to make informed investment decisions.',
        chapters:'5 chapters',
        color:'border-t-pink-400',
        path:'/modules/md?name=technical-analysis'
    },
    {
        id:4,
        title:"Risk Management",
        desc:'Risk Management is the process of identifying, assessing, and controlling threats to an organization’s capital and earnings. In this module, you will learn how to manage risk in your investment portfolio, understand the various types of risks, and implement risk management strategies.',
        chapters:'5 chapters',
        color:'green',
        path:'/modules/md?name=risk-management'
    },
    {
        id:5,
        title:"Sector Analysis",
        desc:'Sector Analysis is the process of evaluating the performance of different sectors of the economy, to identify the best investment opportunities. In this module, you will learn how to analyze the performance of different sectors,  and identify the best sectors to invest in.',
        chapters:'5 chapters',
        color:'yellow',
        path:'/modules/md?name=sector-analysis'
    }
]

export default ModulesData;