import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common-components/Navbar";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Invest IQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <SessionProvider>
          <Navbar/>
        {children}
        </SessionProvider>
        </body>
    </html>
  );
}
